import React from "react";
import { LegalDocumentLayout } from "../components/LegalDocumentLayout";
import { useLanguage } from "../i18n/LanguageContext";

// Written to be accurate to what this app actually does (a grocery-deals browser with
// AI-suggested recipes, sourced from a public flyer API, no account/login) rather than
// generic boilerplate. Replace with real legal copy before shipping to real users.
export function TermsAndConditionsScreen() {
  const { t, language } = useLanguage();

  const sections =
    language === "no"
      ? [
          {
            heading: "Aksept av vilkårene",
            body: "Ved å bruke appen godtar du disse vilkårene. Hvis du ikke godtar dem, bør du ikke bruke appen.",
          },
          {
            heading: "Om tjenesten",
            body: "Appen samler dagens tilbud fra deltakende dagligvarebutikker og foreslår middagsidéer basert på varene du velger. Tilbudsdataene hentes fra butikkenes offentlige ukeavis-tjeneste.",
          },
          {
            heading: "Ingen garanti for pris eller tilgjengelighet",
            body: '"Funnet i denne ukens tilbud" betyr ikke "på lager". Vi viser hva som står i den offentlige ukeavisen, ikke butikkens faktiske lagerbeholdning -- priser, rabatter og tilgjengelighet kan ha endret seg siden avisen ble publisert. Sjekk alltid i butikk før du planlegger rundt et tilbud.',
          },
          {
            heading: "KI-genererte oppskrifter",
            body: "Enkelte oppskrifter og middagsidéer i appen er generert av en språkmodell (KI), ikke skrevet eller kvalitetssikret av en kokk eller ernæringsfysiolog. Bruk sunn fornuft: sjekk alltid ingredienslisten selv, spesielt ved allergier eller spesielle diettbehov, før du lager en rett.",
          },
          {
            heading: "Ingen garantier",
            body: 'Appen leveres "som den er", uten noen garantier -- verken uttrykte eller underforståtte -- om nøyaktighet, pålitelighet eller at tjenesten er feilfri.',
          },
          {
            heading: "Ansvarsbegrensning",
            body: "Vi er ikke ansvarlige for tap eller skade som følge av bruk av appen, inkludert feil i tilbudsdata eller KI-genererte oppskrifter.",
          },
          {
            heading: "Endringer i vilkårene",
            body: "Vi kan oppdatere disse vilkårene fra tid til annen. Fortsatt bruk av appen etter en endring regnes som aksept av de oppdaterte vilkårene.",
          },
          {
            heading: "Kontakt",
            body: "Spørsmål om disse vilkårene kan rettes direkte til oss.",
          },
        ]
      : [
          {
            heading: "Acceptance of terms",
            body: "By using this app, you agree to these terms. If you don't agree with them, please don't use the app.",
          },
          {
            heading: "About the service",
            body: "This app aggregates current discounts from participating grocery stores and suggests meal ideas based on the products you select. Discount data comes from those stores' public weekly-flyer service.",
          },
          {
            heading: "No guarantee of price or availability",
            body: '"Found in this week\'s offers" does not mean "in stock". We show what the public weekly flyer reports, not a store\'s real-time inventory -- prices, discounts, and availability may have changed since the flyer was published. Always check in-store before planning around an offer.',
          },
          {
            heading: "AI-generated recipes",
            body: "Some recipes and meal ideas in this app are generated by a language model (AI), not written or reviewed by a chef or nutritionist. Use common sense: always check the ingredient list yourself, especially for allergies or dietary needs, before cooking a dish.",
          },
          {
            heading: "No warranty",
            body: 'The app is provided "as is", without warranties of any kind -- express or implied -- as to accuracy, reliability, or error-free operation.',
          },
          {
            heading: "Limitation of liability",
            body: "We are not liable for any loss or damage arising from your use of the app, including inaccurate offer data or AI-generated recipes.",
          },
          {
            heading: "Changes to these terms",
            body: "We may update these terms from time to time. Continuing to use the app after a change means you accept the updated terms.",
          },
          {
            heading: "Contact",
            body: "Questions about these terms can be sent directly to us.",
          },
        ];

  return (
    <LegalDocumentLayout
      title={t.termsTitle}
      lastUpdated={t.legalLastUpdated}
      sections={sections}
      testID="terms-and-conditions-screen"
    />
  );
}
